### PR TITLE
issue_#71 resolved

### PR DESCRIPTION
**Pull request by vastavikadi**
### Issue-71 
The mentioned issue has been resolved and been further forwarded for a pull request. Please review and do tell me if there's something wrong.

### Overview
1. Created different important pages.
2. Added footer across the entire web application.
3. Enhanced the overall responsiveness.
4. Fixed Bugs and corrected spellings.

### Request
Do assign Appropriate Level.

### ScreenShots

Screenshot 2024-10-14 200852
Screenshot 2024-10-14 200914
Screenshot 2024-10-14 200934

### CODE REVIEW

**Comment by vastavikadi** [comment]
@Yash-Ainapure is there any issues with this?

**Comment by Yash-Ainapure** [comment]
@vastavikadi ,could you please resolve the merge conflicts?

**Comment by vastavikadi** [comment]
> @vastavikadi ,could you please resolve the merge conflicts?

Can you elaborate a bit more? Is it really going to mess up with the main branch?

**Comment by Yash-Ainapure** [comment]
> > @vastavikadi ,could you please resolve the merge conflicts?
> 
> Can you elaborate a bit more? Is it really going to mess up with the main branch?

There are some merge conflicts for some pages like navbar,herosection,app,about.
try to fix conflicts as possible as you can,I'll fix the webpage later

**Comment by vastavikadi** [comment]
> > > @vastavikadi ,could you please resolve the merge conflicts?
> > 
> > 
> > Can you elaborate a bit more? Is it really going to mess up with the main branch?
> 
> There are some merge conflicts for some pages like navbar,herosection,app,about. try to fix conflicts as possible as you can,I'll fix the webpage later

Done. Please assign me appropriate level, Sir.

**Comment by Yash-Ainapure** [comment]
Thanks for your contributions @vastavikadi .

**Pull request merged**
