### PR TITLE
Solved bug of navbar

### LINKED ISSUE #9: Make Navbar Responsive and Sticky for Improved Mobile Experience
The current navbar lacks responsiveness in mobile view, affecting usability on smaller screens. Additionally, the navbar should be made sticky to improve accessibility during scrolling, as it currently disrupts the user experience. These changes will enhance the overall look and functionality of the navbar across all devices.

Screenshot 2024-10-05 101816
@Yash-Ainapure - Kindly assign me the issue so that I can work on this.

### PR DESCRIPTION
**Pull request by AasthaSingh28**
Closes #9

### CODE REVIEW

**Comment by AasthaSingh28** [comment]
@Yash-Ainapure Hey I don't know I resolved the conflicts but its showing error in deployment.

**Comment by Yash-Ainapure** [comment]
> @Yash-Ainapure Hey I don't know I resolved the conflicts but its showing error in deployment.

There are errors in your code:
src/appComponents/Herosection.tsx(6,6): error TS17008: JSX element 'div' has no corresponding closing tag.
src/appComponents/Herosection.tsx(26,1): error TS1381: Unexpected token. Did you mean `{'}'}` or `&rbrace;`?
src/appComponents/Herosection.tsx(29,1): error TS1005: '</' expected.
Error: Command "npm run build" exited with 2

please reverify your code before pushing it

**Comment by Yash-Ainapure** [comment]
@AasthaSingh28 ,
still the errors are present:
src/appComponents/Herosection.tsx(24,12): error TS1005: ')' expected.
src/appComponents/Herosection.tsx(25,3): error TS1128: Declaration or statement expected.
src/appComponents/Herosection.tsx(26,1): error TS1128: Declaration or statement expected.
Error: Command "npm run build" exited with 2

**Comment by AasthaSingh28** [comment]
Hey @Yash-Ainapure I guess now deployment issues are resolved.

**Comment by Yash-Ainapure** [comment]
I am giving this issue as level 3 due to the effort you have put. 
Thanks for your contributions Aastha.

**Comment by AasthaSingh28** [comment]
@Yash-Ainapure Thanks to you too...

**Pull request merged**
