### PR TITLE
added positions

### PR DESCRIPTION
**Pull request by Gauravtb2253**
Hello I have added some positions in the viewSession page
Pls check it

### CODE REVIEW

**Comment by Gauravtb2253** [comment]
Pls check till the current implementation
what to do next

**Comment by Yash-Ainapure** [comment]
@Gauravtb2253 ,
you got it wrong.
the positions functions are created in backend.
we have to store this info under that club and session id.

**Comment by Gauravtb2253** [comment]
So basically I have to create buttons to add, delete, update hiring positions for each session
and when we click on add , a form will be shown

**Comment by Gauravtb2253** [comment]
check it now pls

**Comment by Yash-Ainapure** [comment]
It works, but still need more improvements in this.

**Comment by Gauravtb2253** [comment]
thank you

**Comment by Gauravtb2253** [comment]
Actually I have some other work for 2 3 days
so is it possible that we continue from sunday if needed

**Comment by Gauravtb2253** [comment]
hello
do you have more issues

**Comment by Yash-Ainapure** [comment]
> hello do you have more issues

Yes.
1.the hiring position,we have implemented ,now we have to add functionality such as delete and upadate to them.

2. we have to display all the hiring sessions to the hiring tab of home page navbar.

3.make the user able to apply for the position/hiring displayed on the hirings tab.

4. display all the applicants to the admin panel

you can try to complete it by making different issue for the above things

**Pull request merged**
