### PR TITLE
Signup Popup and Bugs Removal

### PR DESCRIPTION
**Pull request by NK-Works**
Here's the working video for the login/signup popups-

https://github.com/user-attachments/assets/d7624c8c-5c60-4024-ba4b-13fd55fe2f14

Honestly, please make it a level3 solution...
The sheer amount of bugs in the registration page was horrifying....
I spent around 2 hours just to remove the bugs there to make sure it works as a popup :(

Closes: #177

### CODE REVIEW

**Comment by NK-Works** [comment]
@Yash-Ainapure only 2 days remains would really appreciate if you merge my pr on time

**Comment by NK-Works** [comment]
@Yash-Ainapure @yashksaini-coder @Gauravtb2253 please merge the pr as only a day remains in the GSSOC

**Comment by NK-Works** [comment]
@Yash-Ainapure @yashksaini-coder @Gauravtb2253 please merge the pr as only a day remains in the GSSOC...
At this its a request please dont let my work go waste 🙏

**Comment by Yash-Ainapure** [comment]
@NK-Works ,
really sorry for late .

**Pull request merged**
