### PR TITLE
Updated alignment of footer for responsive 

### PR DESCRIPTION
**Pull request by ChetanSingh14**
#128

### CODE REVIEW

**Comment by Yash-Ainapure** [comment]
@ChetanSingh14 ,
the footer is still white.why?

**Comment by ChetanSingh14** [comment]
@Yash-Ainapure raising another pr for it ?
bcoz of sync fork and git pull

**Comment by Yash-Ainapure** [comment]
> @Yash-Ainapure raising another pr for it ! bcoz of sync fork and git pull

ok

**Comment by ChetanSingh14** [comment]
@Yash-Ainapure have u merged first alignment pr ? bcoz i have to remove code and then add !

**Comment by Yash-Ainapure** [comment]
> @Yash-Ainapure have u merged first alignment pr ? bcoz i have to remove code and then add !

Its not merged

**Comment by ChetanSingh14** [comment]
@Yash-Ainapure please review now !

**Comment by ChetanSingh14** [comment]
@Yash-Ainapure please review it

**Comment by ChetanSingh14** [comment]
@Yash-Ainapure sir please put label on this issue

**Comment by ChetanSingh14** [comment]
@Yash-Ainapure

**Comment by ChetanSingh14** [comment]
@Yash-Ainapure Thank you

**Pull request merged**
