### PR TITLE
fixed page reload on login

### LINKED ISSUE #12: Bug: Club admin login page gets refreshed when we enter login button
To form the Issue: 1.(first create a club admin by registering yourself as admin).  
                                   2.click club login button on home page,
                                   3. enter login credentials.
                                   4. and enter Login button,
                                   : Here the page gets refreshed/rerendered due to some bug and we have to enter the login credentials again.

### PR DESCRIPTION
**Pull request by Swetabh333**
Closes #12 

Fix login functionality to work consistently on first attempt

This PR addresses an issue where the login process was inconsistent, often failing on the first attempt but succeeding on subsequent tries. Key changes include:

- Properly handling asynchronous login in AuthContext
- Implementing correct error handling in the login process
- Ensuring state updates are reflected before navigation
- Preventing premature form submission

These changes resolve the race condition that was causing the inconsistent behavior, resulting in a more reliable login experience for users.

### CODE REVIEW

**Comment by Swetabh333** [comment]
@Yash-Ainapure  I had to make a new fork , can you check it it works now?

**Comment by Swetabh333** [comment]
Can any of the maintainers tell me what the error is?

**Comment by Yash-Ainapure** [comment]
> Can any of the maintainers tell me what the error is?

src/appComponents/ClubLogin.tsx(31,11): error TS1345: An expression of type 'void' cannot be tested for truthiness.
Error: Command "npm run build" exited with 2

**Comment by Swetabh333** [comment]
@Yash-Ainapure is it still failing?

**Comment by Yash-Ainapure** [comment]
> @Yash-Ainapure is it still failing?

Wait we'll check it

**Comment by Swetabh333** [comment]
> Wait we'll check it 

alright

**Comment by Yash-Ainapure** [comment]
Thanks for your contribution

**Pull request merged**
