### PR TITLE
Add auto labeler to assingn auto labels to the issues

### PR DESCRIPTION
**Pull request by shubhagarwal1**

### CODE REVIEW

**Comment by Yash-Ainapure** [comment]
Checks are failing:

Run actions/github-script@v6
TypeError: Cannot read properties of null (reading 'toLowerCase')
    at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15143:16), <anonymous>:24:65)
    at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:151[44](https://github.com/Yash-Ainapure/dypcetclubs.live/actions/runs/11240162196/job/31270446586?pr=51#step:3:45):12)
    at main (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15236:26)
    at /home/runner/work/_actions/actions/github-script/v6/dist/index.js:15217:1
    at /home/runner/work/_actions/actions/github-script/v6/dist/index.js:15268:3
    at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15271:12)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
Error: Unhandled error: TypeError: Cannot read properties of null (reading 'toLowerCase')

**Comment by Yash-Ainapure** [comment]
@Gauravtb2253 ,any updates?

**Comment by Gauravtb2253** [comment]
> @Gauravtb2253 ,any updates?

regarding?

**Comment by Yash-Ainapure** [comment]
> > @Gauravtb2253 ,any updates?
> 
> regarding?

Ohh sorry,i mistakenly mentioned you

**Pull request closed without merging**
