### PR TITLE
add displaying sessions

### PR DESCRIPTION
**Pull request by Gauravtb2253**
Hello
I have added the code to display hiring sessions in the hiring page
Pls check it

### CODE REVIEW

**Comment by Gauravtb2253** [comment]
hello any updates

**Comment by Yash-Ainapure** [comment]
I think we have to show hiring sessions only on the hiring page,not all the clubs

**Comment by Gauravtb2253** [comment]
Actually I displayed for every club separately

**Comment by Gauravtb2253** [comment]
because if we display all at once it may not be good user experience

**Comment by Yash-Ainapure** [comment]
we have to display only the clubs which are hiring currently. not the others which aren't hiring.

**Comment by Gauravtb2253** [comment]
So should I display only the clubs that have data in the hiring positions and remove other clubs from the list

**Comment by Gauravtb2253** [comment]
Pls check it now

**Comment by Gauravtb2253** [comment]
any updates

**Comment by Gauravtb2253** [comment]
hello

**Comment by Yash-Ainapure** [comment]
> hello

Sorry for late,
I'll check it by today

**Comment by Gauravtb2253** [comment]
pls add level label

**Pull request merged**
