### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by Dipanita45**
Added the security for the website 

Fixes : #164 

Please merge my pull request and label me
@Yash-Ainapure

### CODE REVIEW

**Comment by Dipanita45** [comment]
Please merge my pull request and label me
@Yash-Ainapure

**Comment by Dipanita45** [comment]
Please merge my pull request and label me
@Yash-Ainapure

**Comment by Dipanita45** [comment]
Please merge my pull request and label me
@Yash-Ainapure
As tomorrow is the last day

**Comment by Yash-Ainapure** [comment]
Sorry for late @Dipanita45 .

**Comment by Yash-Ainapure** [comment]
thanks for your contribution.

**Pull request merged**
